import type { Metadata } from "next";
import { Container, Section } from "@/components/ui/design-system";

export const metadata: Metadata = { title: "Website Terms", description: "Terms governing use of the NileBit Labs public website.", alternates: { canonical: "/terms" } };

const sections = [
  ["About these terms", "These terms apply to use of the public NileBit Labs website. They do not replace a proposal, statement of work, service agreement, or other contract for client services. Project scope, fees, payment terms, ownership, warranties, support, and liability are agreed separately for each engagement."],
  ["Website content", "We provide this website for general information about NileBit Labs and our capabilities. We aim to keep it useful and accurate, but website content is not professional advice, a binding offer, or a guarantee that a particular service or outcome is available."],
  ["Acceptable use", "You may not misuse the website, attempt unauthorized access, interfere with its operation, submit unlawful or harmful material, or use automated methods in a way that places an unreasonable burden on the service."],
  ["Intellectual property", "Unless stated otherwise, NileBit Labs or its licensors own the website design, text, branding, and other original material. You may view and share links to public pages, but you may not reproduce or commercially reuse substantial content without permission."],
  ["Third-party services", "Links and integrations may lead to services operated by others. We do not control those services and are not responsible for their content, availability, or practices."],
  ["Availability and responsibility", "We may update, suspend, or withdraw parts of the website. To the extent permitted by applicable law, the website is provided without promises that it will always be available or error-free. Nothing in these terms excludes responsibility that cannot legally be excluded."],
  ["Changes", "We may revise these website terms when the site or applicable requirements change. The current version will appear on this page with its effective date."],
] as const;

export default function TermsPage() { return <div><Section spacing="lg"><Container size="content"><p className="text-eyebrow text-primary">Legal</p><h1 className="mt-6 text-heading-1 text-heading">Website Terms</h1><p className="mt-6 text-body-lg text-muted">Terms for using the public NileBit Labs website. Client work is governed by a separate written agreement.</p><p className="mt-5 text-caption text-muted">Effective August 11, 2026</p></Container></Section><Section tone="surface" spacing="lg"><Container size="content"><div className="space-y-10">{sections.map(([heading, body]) => <section key={heading}><h2 className="text-heading-3 text-heading">{heading}</h2><p className="mt-4 text-body-lg text-muted">{body}</p></section>)}<section><h2 className="text-heading-3 text-heading">Contact</h2><p className="mt-4 text-body-lg text-muted">Questions about these terms can be sent to <a href="mailto:info@nilebitlabs.com" className="text-heading underline underline-offset-4 hover:text-primary">info@nilebitlabs.com</a>.</p></section></div></Container></Section></div>; }
